---
- name: Fail if required matrix-appservice-double-puppet settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'matrix_appservice_double_puppet_registration_as_token', when: true}
    - {'name': 'matrix_appservice_double_puppet_registration_as_token', when: true}
    - {'name': 'matrix_appservice_double_puppet_registration_sender_localpart', when: true}
